### ISSUE TITLE
still working ?

### ISSUE THREAD

**Issue by dolodi** [adrianmontes23/MySingingMonstersAutoBot#1]
If its just photo recognition shouldnt it still work?

**Comment by adrianmontes23** [comment]
> If its just photo recognition shouldnt it still work?

The problem is, this code was made before the "improved" map update. I haven't changed the code since. Here's a clip of it working before that update: https://youtube.com/clip/UgkxKby417Szf91RVENLPVlmSMG9xQknf3tB?si=bwRoikcEYvLKSeyK
